[package]
name = "dnscache"
version = "0.1.1"
edition = "2024"

[dependencies]
dashmap = "5"
num_cpus = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[profile.release]
overflow-checks = true
