[toolchain]
channel = "stable"
profile = "minimal"

components = [
    "rustfmt",
    "clippy"
]

targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",

    "x86_64-apple-darwin",
    "aarch64-apple-darwin",

    "x86_64-pc-windows-msvc",

    "x86_64-unknown-freebsd"
]
